<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        DB::table('districts')->insert([
          [ 'id' => 1, 'province_id' => 4, 'name' => 'Abra, Lone'],
          [ 'id' => 2, 'province_id' => 72, 'name' => 'Agusan del Norte, 1st'],
          [ 'id' => 3, 'province_id' => 72, 'name' => 'Agusan del Norte, 2nd'],
          [ 'id' => 4, 'province_id' => 73, 'name' => 'Agusan del Sur, 1st'],
          [ 'id' => 5, 'province_id' => 73, 'name' => 'Agusan del Sur, 2nd'],
          [ 'id' => 6, 'province_id' => 40, 'name' => 'Aklan, 1st'],
          [ 'id' => 7, 'province_id' => 40, 'name' => 'Aklan, 2nd'],
          [ 'id' => 8, 'province_id' => 36, 'name' => 'Albay, 1st'],
          [ 'id' => 9, 'province_id' => 36, 'name' => 'Albay, 2nd'],
          [ 'id' => 10, 'province_id' => 36, 'name' => 'Albay, 3rd'],
          [ 'id' => 11, 'province_id' => 23, 'name' => 'Antipolo, 1st'],
          [ 'id' => 12, 'province_id' => 23, 'name' => 'Antipolo, 2nd'],
          [ 'id' => 13, 'province_id' => 41, 'name' => 'Antique, Lone'],
          [ 'id' => 14, 'province_id' => 5, 'name' => 'Apayao, Lone'],
          [ 'id' => 15, 'province_id' => 22, 'name' => 'Aurora, Lone'],
          [ 'id' => 16, 'province_id' => 45, 'name' => 'Bacolod, Lone'],
          [ 'id' => 17, 'province_id' => 3, 'name' => 'Baguio, Lone'],
          [ 'id' => 18, 'province_id' => 78, 'name' => 'Basilan, Lone'],
          [ 'id' => 19, 'province_id' => 16, 'name' => 'Bataan, 1st'],
          [ 'id' => 20, 'province_id' => 16, 'name' => 'Bataan, 2nd'],
          [ 'id' => 21, 'province_id' => 15, 'name' => 'Batanes, Lone'],
          [ 'id' => 22, 'province_id' => 26, 'name' => 'Batangas, 1st'],
          [ 'id' => 23, 'province_id' => 26, 'name' => 'Batangas, 2nd'],
          [ 'id' => 24, 'province_id' => 26, 'name' => 'Batangas, 3rd'],
          [ 'id' => 25, 'province_id' => 26, 'name' => 'Batangas, 4th'],
          [ 'id' => 26, 'province_id' => 26, 'name' => 'Batangas, 5th'],
          [ 'id' => 27, 'province_id' => 26, 'name' => 'Batangas, 6th'],
          [ 'id' => 28, 'province_id' => 3, 'name' => 'Benguet, Lone'],
          [ 'id' => 29, 'province_id' => 54, 'name' => 'Biliran, Lone'],
          [ 'id' => 30, 'province_id' => 25, 'name' => 'Biñan, Lone'],
          [ 'id' => 31, 'province_id' => 47, 'name' => 'Bohol, 1st'],
          [ 'id' => 32, 'province_id' => 47, 'name' => 'Bohol, 2nd'],
          [ 'id' => 33, 'province_id' => 47, 'name' => 'Bohol, 3rd'],
          [ 'id' => 34, 'province_id' => 59, 'name' => 'Bukidnon, 1st'],
          [ 'id' => 35, 'province_id' => 59, 'name' => 'Bukidnon, 2nd'],
          [ 'id' => 36, 'province_id' => 59, 'name' => 'Bukidnon, 3rd'],
          [ 'id' => 37, 'province_id' => 59, 'name' => 'Bukidnon, 4th'],
          [ 'id' => 38, 'province_id' => 20, 'name' => 'Bulacan, 1st'],
          [ 'id' => 39, 'province_id' => 20, 'name' => 'Bulacan, 2nd'],
          [ 'id' => 40, 'province_id' => 20, 'name' => 'Bulacan, 3rd'],
          [ 'id' => 41, 'province_id' => 20, 'name' => 'Bulacan, 4th'],
          [ 'id' => 42, 'province_id' => 12, 'name' => 'Cagayan, 1st'],
          [ 'id' => 43, 'province_id' => 12, 'name' => 'Cagayan, 2nd'],
          [ 'id' => 44, 'province_id' => 12, 'name' => 'Cagayan, 3rd'],
          [ 'id' => 45, 'province_id' => 93, 'name' => 'Cagayan de Oro, 1st'],
          [ 'id' => 46, 'province_id' => 93, 'name' => 'Cagayan de Oro, 2nd'],
          [ 'id' => 47, 'province_id' => 25, 'name' => 'Calamba, Lone'],
          [ 'id' => 48, 'province_id' => 84, 'name' => 'Caloocan, 1st'],
          [ 'id' => 49, 'province_id' => 84, 'name' => 'Caloocan, 2nd'],
          [ 'id' => 50, 'province_id' => 34, 'name' => 'Camarines Norte, 1st'],
          [ 'id' => 51, 'province_id' => 34, 'name' => 'Camarines Norte, 2nd'],
          [ 'id' => 52, 'province_id' => 38, 'name' => 'Camarines Sur, 1st'],
          [ 'id' => 53, 'province_id' => 38, 'name' => 'Camarines Sur, 2nd'],
          [ 'id' => 54, 'province_id' => 38, 'name' => 'Camarines Sur, 3rd'],
          [ 'id' => 55, 'province_id' => 38, 'name' => 'Camarines Sur, 4th'],
          [ 'id' => 56, 'province_id' => 38, 'name' => 'Camarines Sur, 5th'],
          [ 'id' => 57, 'province_id' => 62, 'name' => 'Camiguin, Lone'],
          [ 'id' => 58, 'province_id' => 39, 'name' => 'Capiz, 1st'],
          [ 'id' => 59, 'province_id' => 39, 'name' => 'Capiz, 2nd'],
          [ 'id' => 60, 'province_id' => 33, 'name' => 'Catanduanes, Lone'],
          [ 'id' => 61, 'province_id' => 24, 'name' => 'Cavite, 1st'],
          [ 'id' => 62, 'province_id' => 24, 'name' => 'Cavite, 2nd'],
          [ 'id' => 63, 'province_id' => 24, 'name' => 'Cavite, 3rd'],
          [ 'id' => 64, 'province_id' => 24, 'name' => 'Cavite, 4th'],
          [ 'id' => 65, 'province_id' => 24, 'name' => 'Cavite, 5th'],
          [ 'id' => 66, 'province_id' => 24, 'name' => 'Cavite, 6th'],
          [ 'id' => 67, 'province_id' => 24, 'name' => 'Cavite, 7th'],
          [ 'id' => 68, 'province_id' => 24, 'name' => 'Cavite, 8th'],
          [ 'id' => 69, 'province_id' => 46, 'name' => 'Cebu, 1st'],
          [ 'id' => 70, 'province_id' => 46, 'name' => 'Cebu, 2nd'],
          [ 'id' => 71, 'province_id' => 46, 'name' => 'Cebu, 3rd'],
          [ 'id' => 72, 'province_id' => 46, 'name' => 'Cebu, 4th'],
          [ 'id' => 73, 'province_id' => 46, 'name' => 'Cebu, 5th'],
          [ 'id' => 74, 'province_id' => 46, 'name' => 'Cebu, 6th'],
          [ 'id' => 75, 'province_id' => 46, 'name' => 'Cebu, 7th'],
          [ 'id' => 76, 'province_id' => 46, 'name' => 'Cebu City, 1st'],
          [ 'id' => 77, 'province_id' => 46, 'name' => 'Cebu City, 2nd'],
          [ 'id' => 78, 'province_id' => 64, 'name' => 'Compostela Valley, 1st'],
          [ 'id' => 79, 'province_id' => 64, 'name' => 'Compostela Valley, 2nd'],
          [ 'id' => 80, 'province_id' => 70, 'name' => 'Cotabato, 1st'],
          [ 'id' => 81, 'province_id' => 70, 'name' => 'Cotabato, 2nd'],
          [ 'id' => 82, 'province_id' => 70, 'name' => 'Cotabato, 3rd'],
          [ 'id' => 83, 'province_id' => 87, 'name' => 'Davao City, 1st'],
          [ 'id' => 84, 'province_id' => 87, 'name' => 'Davao City, 2nd'],
          [ 'id' => 85, 'province_id' => 87, 'name' => 'Davao City, 3rd'],
          [ 'id' => 86, 'province_id' => 67, 'name' => 'Davao del Norte, 1st'],
          [ 'id' => 87, 'province_id' => 67, 'name' => 'Davao del Norte, 2nd'],
          [ 'id' => 88, 'province_id' => 65, 'name' => 'Davao del Sur, Lone'],
          [ 'id' => 89, 'province_id' => 66, 'name' => 'Davao Occidental, Lone'],
          [ 'id' => 90, 'province_id' => 63, 'name' => 'Davao Oriental, 1st'],
          [ 'id' => 91, 'province_id' => 63, 'name' => 'Davao Oriental, 2nd'],
          [ 'id' => 92, 'province_id' => 76, 'name' => 'Dinagat Islands, Lone'],
          [ 'id' => 93, 'province_id' => 50, 'name' => 'Eastern Samar, Lone'],
          [ 'id' => 94, 'province_id' => 44, 'name' => 'Guimaras, Lone'],
          [ 'id' => 95, 'province_id' => 2, 'name' => 'Ifugao, Lone'],
          [ 'id' => 96, 'province_id' => 92, 'name' => 'Iligan, Lone'],
          [ 'id' => 97, 'province_id' => 8, 'name' => 'Ilocos Norte, 1st'],
          [ 'id' => 98, 'province_id' => 8, 'name' => 'Ilocos Norte, 2nd'],
          [ 'id' => 99, 'province_id' => 9, 'name' => 'Ilocos Sur, 1st'],
          [ 'id' => 100, 'province_id' => 9, 'name' => 'Ilocos Sur, 2nd'],
          [ 'id' => 101, 'province_id' => 43, 'name' => 'Iloilo, 1st'],
          [ 'id' => 102, 'province_id' => 43, 'name' => 'Iloilo, 2nd'],
          [ 'id' => 103, 'province_id' => 43, 'name' => 'Iloilo, 3rd'],
          [ 'id' => 104, 'province_id' => 43, 'name' => 'Iloilo, 4th'],
          [ 'id' => 105, 'province_id' => 43, 'name' => 'Iloilo, 5th'],
          [ 'id' => 106, 'province_id' => 88, 'name' => 'Iloilo City, Lone'],
          [ 'id' => 107, 'province_id' => 13, 'name' => 'Isabela, 1st'],
          [ 'id' => 108, 'province_id' => 13, 'name' => 'Isabela, 2nd'],
          [ 'id' => 109, 'province_id' => 13, 'name' => 'Isabela, 3rd'],
          [ 'id' => 110, 'province_id' => 13, 'name' => 'Isabela, 4th'],
          [ 'id' => 111, 'province_id' => 13, 'name' => 'Isabela, 5th'],
          [ 'id' => 112, 'province_id' => 13, 'name' => 'Isabela, 6th'],
          [ 'id' => 113, 'province_id' => 6, 'name' => 'Kalinga, Lone'],
          [ 'id' => 114, 'province_id' => 7, 'name' => 'La Union, 1st'],
          [ 'id' => 115, 'province_id' => 7, 'name' => 'La Union, 2nd'],
          [ 'id' => 116, 'province_id' => 25, 'name' => 'Laguna, 1st'],
          [ 'id' => 117, 'province_id' => 25, 'name' => 'Laguna, 2nd'],
          [ 'id' => 118, 'province_id' => 25, 'name' => 'Laguna, 3rd'],
          [ 'id' => 119, 'province_id' => 25, 'name' => 'Laguna, 4th'],
          [ 'id' => 120, 'province_id' => 60, 'name' => 'Lanao del Norte, 1st'],
          [ 'id' => 121, 'province_id' => 60, 'name' => 'Lanao del Norte, 2nd'],
          [ 'id' => 122, 'province_id' => 81, 'name' => 'Lanao del Sur, 1st'],
          [ 'id' => 123, 'province_id' => 81, 'name' => 'Lanao del Sur, 2nd'],
          [ 'id' => 124, 'province_id' => 46, 'name' => 'Lapu-Lapu City, Lone'],
          [ 'id' => 125, 'province_id' => 85, 'name' => 'Las Piñas, Lone'],
          [ 'id' => 126, 'province_id' => 53, 'name' => 'Leyte, 1st'],
          [ 'id' => 127, 'province_id' => 53, 'name' => 'Leyte, 2nd'],
          [ 'id' => 128, 'province_id' => 53, 'name' => 'Leyte, 3rd'],
          [ 'id' => 129, 'province_id' => 53, 'name' => 'Leyte, 4th'],
          [ 'id' => 130, 'province_id' => 53, 'name' => 'Leyte, 5th'],
          [ 'id' => 131, 'province_id' => 80, 'name' => 'Maguindanao, 1st'],
          [ 'id' => 132, 'province_id' => 80, 'name' => 'Maguindanao, 2nd'],
          [ 'id' => 133, 'province_id' => 85, 'name' => 'Makati, 1st'],
          [ 'id' => 134, 'province_id' => 85, 'name' => 'Makati, 2nd'],
          [ 'id' => 135, 'province_id' => 84, 'name' => 'Malabon, Lone'],
          [ 'id' => 136, 'province_id' => 83, 'name' => 'Mandaluyong, Lone'],
          [ 'id' => 137, 'province_id' => 82, 'name' => 'Manila, 1st'],
          [ 'id' => 138, 'province_id' => 82, 'name' => 'Manila, 2nd'],
          [ 'id' => 139, 'province_id' => 82, 'name' => 'Manila, 3rd'],
          [ 'id' => 140, 'province_id' => 82, 'name' => 'Manila, 4th'],
          [ 'id' => 141, 'province_id' => 82, 'name' => 'Manila, 5th'],
          [ 'id' => 142, 'province_id' => 82, 'name' => 'Manila, 6th'],
          [ 'id' => 143, 'province_id' => 82, 'name' => 'Marikina, 1st'],
          [ 'id' => 144, 'province_id' => 82, 'name' => 'Marikina, 2nd'],
          [ 'id' => 145, 'province_id' => 32, 'name' => 'Marinduque, Lone'],
          [ 'id' => 146, 'province_id' => 37, 'name' => 'Masbate, 1st'],
          [ 'id' => 147, 'province_id' => 37, 'name' => 'Masbate, 2nd'],
          [ 'id' => 148, 'province_id' => 37, 'name' => 'Masbate, 3rd'],
          [ 'id' => 149, 'province_id' => 58, 'name' => 'Misamis Occidental, 1st'],
          [ 'id' => 150, 'province_id' => 58, 'name' => 'Misamis Occidental, 2nd'],
          [ 'id' => 151, 'province_id' => 61, 'name' => 'Misamis Oriental, 1st'],
          [ 'id' => 152, 'province_id' => 61, 'name' => 'Misamis Oriental, 2nd'],
          [ 'id' => 153, 'province_id' => 1, 'name' => 'Mountain Province, Lone'],
          [ 'id' => 154, 'province_id' => 85, 'name' => 'Muntinlupa, Lone'],
          [ 'id' => 155, 'province_id' => 84, 'name' => 'Navotas, Lone'],
          [ 'id' => 156, 'province_id' => 42, 'name' => 'Negros Occidental, 1st'],
          [ 'id' => 157, 'province_id' => 42, 'name' => 'Negros Occidental, 2nd'],
          [ 'id' => 158, 'province_id' => 42, 'name' => 'Negros Occidental, 3rd'],
          [ 'id' => 159, 'province_id' => 42, 'name' => 'Negros Occidental, 4th'],
          [ 'id' => 160, 'province_id' => 42, 'name' => 'Negros Occidental, 5th'],
          [ 'id' => 161, 'province_id' => 42, 'name' => 'Negros Occidental, 6th'],
          [ 'id' => 162, 'province_id' => 45, 'name' => 'Negros Oriental, 1st'],
          [ 'id' => 163, 'province_id' => 45, 'name' => 'Negros Oriental, 2nd'],
          [ 'id' => 164, 'province_id' => 45, 'name' => 'Negros Oriental, 3rd'],
          [ 'id' => 165, 'province_id' => 51, 'name' => 'Northern Samar, 1st'],
          [ 'id' => 166, 'province_id' => 51, 'name' => 'Northern Samar, 2nd'],
          [ 'id' => 167, 'province_id' => 21, 'name' => 'Nueva Ecija, 1st'],
          [ 'id' => 168, 'province_id' => 21, 'name' => 'Nueva Ecija, 2nd'],
          [ 'id' => 169, 'province_id' => 21, 'name' => 'Nueva Ecija, 3rd'],
          [ 'id' => 170, 'province_id' => 21, 'name' => 'Nueva Ecija, 4th'],
          [ 'id' => 171, 'province_id' => 11, 'name' => 'Nueva Vizcaya, Lone'],
          [ 'id' => 172, 'province_id' => 28, 'name' => 'Occidental Mindoro, Lone'],
          [ 'id' => 173, 'province_id' => 29, 'name' => 'Oriental Mindoro, 1st'],
          [ 'id' => 174, 'province_id' => 29, 'name' => 'Oriental Mindoro, 2nd'],
          [ 'id' => 175, 'province_id' => 31, 'name' => 'Palawan, 1st'],
          [ 'id' => 176, 'province_id' => 31, 'name' => 'Palawan, 2nd'],
          [ 'id' => 177, 'province_id' => 31, 'name' => 'Palawan, 3rd'],
          [ 'id' => 178, 'province_id' => 19, 'name' => 'Pampanga, 1st'],
          [ 'id' => 179, 'province_id' => 19, 'name' => 'Pampanga, 2nd'],
          [ 'id' => 180, 'province_id' => 19, 'name' => 'Pampanga, 3rd'],
          [ 'id' => 181, 'province_id' => 19, 'name' => 'Pampanga, 4th'],
          [ 'id' => 182, 'province_id' => 10, 'name' => 'Pangasinan, 1st'],
          [ 'id' => 183, 'province_id' => 10, 'name' => 'Pangasinan, 2nd'],
          [ 'id' => 184, 'province_id' => 10, 'name' => 'Pangasinan, 3rd'],
          [ 'id' => 185, 'province_id' => 10, 'name' => 'Pangasinan, 4th'],
          [ 'id' => 186, 'province_id' => 10, 'name' => 'Pangasinan, 5th'],
          [ 'id' => 187, 'province_id' => 10, 'name' => 'Pangasinan, 6th'],
          [ 'id' => 188, 'province_id' => 85, 'name' => 'Parañaque, 1st'],
          [ 'id' => 189, 'province_id' => 85, 'name' => 'Parañaque, 2nd'],
          [ 'id' => 190, 'province_id' => 83, 'name' => 'Pasay, Lone'],
          [ 'id' => 191, 'province_id' => 85, 'name' => 'Pasig, Lone'],
          [ 'id' => 192, 'province_id' => 27, 'name' => 'Quezon, 1st'],
          [ 'id' => 193, 'province_id' => 27, 'name' => 'Quezon, 2nd'],
          [ 'id' => 194, 'province_id' => 27, 'name' => 'Quezon, 3rd'],
          [ 'id' => 195, 'province_id' => 27, 'name' => 'Quezon, 4th'],
          [ 'id' => 196, 'province_id' => 83, 'name' => 'Quezon City, 1st'],
          [ 'id' => 197, 'province_id' => 83, 'name' => 'Quezon City, 2nd'],
          [ 'id' => 198, 'province_id' => 83, 'name' => 'Quezon City, 3rd'],
          [ 'id' => 199, 'province_id' => 83, 'name' => 'Quezon City, 4th'],
          [ 'id' => 200, 'province_id' => 83, 'name' => 'Quezon City, 5th'],
          [ 'id' => 201, 'province_id' => 83, 'name' => 'Quezon City, 6th'],
          [ 'id' => 202, 'province_id' => 14, 'name' => 'Quirino, Lone'],
          [ 'id' => 203, 'province_id' => 23, 'name' => 'Rizal, 1st'],
          [ 'id' => 204, 'province_id' => 23, 'name' => 'Rizal, 2nd'],
          [ 'id' => 205, 'province_id' => 30, 'name' => 'Romblon, Lone'],
          [ 'id' => 206, 'province_id' => 52, 'name' => 'Samar, 1st'],
          [ 'id' => 207, 'province_id' => 52, 'name' => 'Samar, 2nd'],
          [ 'id' => 208, 'province_id' => 20, 'name' => 'San Jose del Monte, Lone'],
          [ 'id' => 209, 'province_id' => 83, 'name' => 'San Juan, Lone'],
          [ 'id' => 210, 'province_id' => 71, 'name' => 'Sarangani, Lone'],
          [ 'id' => 211, 'province_id' => 48, 'name' => 'Siquijor, Lone'],
          [ 'id' => 212, 'province_id' => 35, 'name' => 'Sorsogon, 1st'],
          [ 'id' => 213, 'province_id' => 35, 'name' => 'Sorsogon, 2nd'],
          [ 'id' => 214, 'province_id' => 68, 'name' => 'South Cotabato, 1st'],
          [ 'id' => 215, 'province_id' => 68, 'name' => 'South Cotabato, 2nd'],
          [ 'id' => 216, 'province_id' => 49, 'name' => 'Southern Leyte, Lone'],
          [ 'id' => 217, 'province_id' => 69, 'name' => 'Sultan Kudarat, 1st'],
          [ 'id' => 218, 'province_id' => 69, 'name' => 'Sultan Kudarat, 2nd'],
          [ 'id' => 219, 'province_id' => 79, 'name' => 'Sulu, 1st'],
          [ 'id' => 220, 'province_id' => 79, 'name' => 'Sulu, 2nd'],
          [ 'id' => 221, 'province_id' => 75, 'name' => 'Surigao del Norte, 1st'],
          [ 'id' => 222, 'province_id' => 75, 'name' => 'Surigao del Norte, 2nd'],
          [ 'id' => 223, 'province_id' => 74, 'name' => 'Surigao del Sur, 1st'],
          [ 'id' => 224, 'province_id' => 74, 'name' => 'Surigao del Sur, 2nd'],
          [ 'id' => 225, 'province_id' => 85, 'name' => 'Taguig–Pateros, 1st'],
          [ 'id' => 226, 'province_id' => 85, 'name' => 'Taguig, 2nd'],
          [ 'id' => 227, 'province_id' => 18, 'name' => 'Tarlac, 1st'],
          [ 'id' => 228, 'province_id' => 18, 'name' => 'Tarlac, 2nd'],
          [ 'id' => 229, 'province_id' => 18, 'name' => 'Tarlac, 3rd'],
          [ 'id' => 230, 'province_id' => 77, 'name' => 'Tawi-Tawi, Lone'],
          [ 'id' => 231, 'province_id' => 84, 'name' => 'Valenzuela, 1st'],
          [ 'id' => 232, 'province_id' => 84, 'name' => 'Valenzuela, 2nd'],
          [ 'id' => 233, 'province_id' => 17, 'name' => 'Zambales, 1st'],
          [ 'id' => 234, 'province_id' => 17, 'name' => 'Zambales, 2nd'],
          [ 'id' => 235, 'province_id' => 86, 'name' => 'Zamboanga City, 1st'],
          [ 'id' => 236, 'province_id' => 86, 'name' => 'Zamboanga City, 2nd'],
          [ 'id' => 237, 'province_id' => 56, 'name' => 'Zamboanga del Norte, 1st'],
          [ 'id' => 238, 'province_id' => 56, 'name' => 'Zamboanga del Norte, 2nd'],
          [ 'id' => 239, 'province_id' => 56, 'name' => 'Zamboanga del Norte, 3rd'],
          [ 'id' => 240, 'province_id' => 57, 'name' => 'Zamboanga del Sur, 1st'],
          [ 'id' => 241, 'province_id' => 57, 'name' => 'Zamboanga del Sur, 2nd'],
          [ 'id' => 242, 'province_id' => 55, 'name' => 'Zamboanga Sibugay, 1st'],
          [ 'id' => 243, 'province_id' => 55, 'name' => 'Zamboanga Sibugay, 2nd']
        ]);
    }
}
